on:
  push:
    tags:
      - '*'

name: nextgen Create Image and Deployment

jobs:

  push:
    name: Push to registry and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Login to GitLab
      uses: docker/login-action@v1
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}

    - uses: actions/checkout@v2

    - name: Get Hash and Refs
      id: vars
      shell: bash
      run: |
        echo "::set-output name=version_tag::${GITHUB_REF/refs\/tags\//}"
    - name: Check Hash
      run: echo "${{ steps.vars.outputs.version_tag }}"

    - name: Create env file
      run: |
        touch .env
        echo APP_ENV=production >> .env
        echo APP_KEY=${{ secrets.PHP_ENV_PROD_APP_KEY }} >> .env
        echo APP_DEBUG=true >> .env
        echo DB_CONNECTION=mysql >> .env
        echo DB_HOST=135.181.42.112 >> .env
        echo DB_PORT=3306 >> .env
        echo DB_DATABASE=nextgen >> .env
        echo DB_USERNAME=nextgen >> .env
        echo DB_PASSWORD=${{ secrets.PHP_ENV_PROD_DB_PASSWORD }} >> .env
        cat .env
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          registry.gitlab.com/arvin.s.corpuz/limitless/nextgen:${{ steps.vars.outputs.version_tag }}
          registry.gitlab.com/arvin.s.corpuz/limitless/nextgen:latest
    - uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.23.0'
      id: install

    - uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        context: limitlessv2

    - name: Run PHP Artisan Migrate Refresh
      run: |
        php artisan migrate:refresh --path=/database/migrations/2025_05_21_123622_create_codesettings_table.php

    - name: Deploy
      run: |
        kubectl version
        kubectl rollout restart deployment nextgen -n nextgen